# Affine alignment applied before deformable alignment

# saved results
save_path_root: 'C:\dev_personal\Thesis\training_results'

# model
moving_image_shape: [24, 24, 24, 1]  # ultrasound volumes, channel-last
fixed_image_shape: [24, 24, 24, 1]   # MR volumes, channel-last
up_filters: [64, 128]
down_filters: [128, 64, 32]

# caching
train_path: 'C:\dev_personal\Thesis\src\Affine_Alignment\preproc_data_train\train'
val_path: 'C:\dev_personal\Thesis\src\Affine_Alignment\preproc_data_val\val'
